import { configurePhotoPool } from '@core/index'

import manifest from './demo-photos.json'

/**
 * U9 (2026-09-02) — THE POOL OF CC0 PHOTOGRAPHS THE DEMO MARKERS RESOLVE TO.
 *
 * `demo-photos.json` is generated by `bun run scripts/demo-photos.ts` from
 * `public/demo-photos/manifest.json` — every file in it was verified CC0 /
 * public domain through the Wikimedia Commons API (`extmetadata`), and the
 * provenance of each is in `docs/demo-photos-licences.md`. The files are
 * static assets of the app, served from its own origin, so they work
 * offline once cached and need no bucket, no session and no purge.
 *
 * Configured before the first render (see `main.tsx`); an empty list — the
 * gates, a build without the assets — leaves the stylised portraits in place.
 */
export function installDemoPhotos(): void {
  const base = import.meta.env.BASE_URL
  const url = (file: string) => `${base}demo-photos/${file.replace(/^\//, '')}`
  configurePhotoPool({
    person: manifest.people.map(url),
    place: manifest.places.map(url),
  })
}
